// Generated by gencpp from file open_motor_msgs/feedback.msg
// DO NOT EDIT!


#ifndef OPEN_MOTOR_MSGS_MESSAGE_FEEDBACK_H
#define OPEN_MOTOR_MSGS_MESSAGE_FEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace open_motor_msgs
{
template <class ContainerAllocator>
struct feedback_
{
  typedef feedback_<ContainerAllocator> Type;

  feedback_()
    : position()
    , velocity()  {
      position.assign(0);

      velocity.assign(0.0);
  }
  feedback_(const ContainerAllocator& _alloc)
    : position()
    , velocity()  {
  (void)_alloc;
      position.assign(0);

      velocity.assign(0.0);
  }



   typedef boost::array<int32_t, 4>  _position_type;
  _position_type position;

   typedef boost::array<float, 4>  _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::open_motor_msgs::feedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::open_motor_msgs::feedback_<ContainerAllocator> const> ConstPtr;

}; // struct feedback_

typedef ::open_motor_msgs::feedback_<std::allocator<void> > feedback;

typedef boost::shared_ptr< ::open_motor_msgs::feedback > feedbackPtr;
typedef boost::shared_ptr< ::open_motor_msgs::feedback const> feedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::open_motor_msgs::feedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::open_motor_msgs::feedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::open_motor_msgs::feedback_<ContainerAllocator1> & lhs, const ::open_motor_msgs::feedback_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::open_motor_msgs::feedback_<ContainerAllocator1> & lhs, const ::open_motor_msgs::feedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace open_motor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::open_motor_msgs::feedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open_motor_msgs::feedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_motor_msgs::feedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_motor_msgs::feedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_motor_msgs::feedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_motor_msgs::feedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::open_motor_msgs::feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31bb560d0afc21aab3c9b7d796411992";
  }

  static const char* value(const ::open_motor_msgs::feedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31bb560d0afc21aaULL;
  static const uint64_t static_value2 = 0xb3c9b7d796411992ULL;
};

template<class ContainerAllocator>
struct DataType< ::open_motor_msgs::feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "open_motor_msgs/feedback";
  }

  static const char* value(const ::open_motor_msgs::feedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::open_motor_msgs::feedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header header\n"
"int32[4] position\n"
"float32[4] velocity\n"
;
  }

  static const char* value(const ::open_motor_msgs::feedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::open_motor_msgs::feedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct feedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::open_motor_msgs::feedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::open_motor_msgs::feedback_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocity[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPEN_MOTOR_MSGS_MESSAGE_FEEDBACK_H
